//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FTN.Common;

namespace FTN.Services.NetworkModelService.DataModel.Core
{ 
    
    /// The parts of the power system that are designed to carry current or that are conductively connected through terminals.
    public class ConductingEquipment : Equipment {
    }
}
