//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FTN.Common;

namespace FTN.Services.NetworkModelService.DataModel.Core
{
    /// The schedule has time points where the time between them varies.
    public class IrregularIntervalSchedule : BasicIntervalSchedule {
    }
}
