//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FTN.Common;
using FTN.Services.NetworkModelService.DataModel.Core;
using FTN.Services.NetworkModelService.DataModel.Outage;

namespace FTN.Services.NetworkModelService.DataModel.Wires
{
    /// A generic device designed to close, or open, or both, one or more electric circuits.
    public class Switch : ConductingEquipment {
        
        /// A switch may be operated by many schedules.
        private SwitchingOperation cim_SwitchingOperations;
        
        private const bool isSwitchingOperationsMandatory = false;
        
        private const string _SwitchingOperationsPrefix = "cim";
        
        public virtual SwitchingOperation SwitchingOperations {
            get {
                return this.cim_SwitchingOperations;
            }
            set {
                this.cim_SwitchingOperations = value;
            }
        }
        
        public virtual bool SwitchingOperationsHasValue {
            get {
                return this.cim_SwitchingOperations != null;
            }
        }
        
        public static bool IsSwitchingOperationsMandatory {
            get {
                return isSwitchingOperationsMandatory;
            }
        }
        
        public static string SwitchingOperationsPrefix {
            get {
                return _SwitchingOperationsPrefix;
            }
        }
    }
}
